In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Sum of Two Vector Or Matrix

In [ ]:
a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,0,0,0])
a + b

In [ ]:
X = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

Y = [[9, 8, 7],
     [6, 5, 4],
     [3, 2, 1]]

result = np.array(X) + np.array(Y)

print(result)

# BroadCasing 

In [ ]:
a = np.array([1,2,3,4,5,6])
b = a + 10
b

# Eye

In [ ]:
np.eye(10)

In [12]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
a = np.eye(3,3)
a.ndim

2

In [ ]:
np.zeros(5)

# Zeros

In [10]:
np.zeros((6,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

# Ones

In [7]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [9]:
a = np.ones((5,6))
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# Number of dimention

In [31]:
a = np.ones((5,6))
print(a.ndim)
print(a.size)

2
30


# Arragne

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
np.arange(5,20, .5)

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ,
       10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

# Random

In [23]:
np.random.rand(3,2)

array([[0.50884231, 0.33969244],
       [0.01375317, 0.1927339 ],
       [0.9720803 , 0.24092031]])

# Aggrigation

In [32]:
a = np.random.rand(5,5)
a

array([[0.5559181 , 0.86377717, 0.9160167 , 0.11753341, 0.95843289],
       [0.7619494 , 0.18774452, 0.32575622, 0.26715433, 0.97205537],
       [0.06644956, 0.83741505, 0.7407686 , 0.69563695, 0.81746517],
       [0.64648099, 0.1098461 , 0.80420634, 0.5643329 , 0.91446008],
       [0.66706086, 0.08786254, 0.42166753, 0.4770074 , 0.98906293]])

In [33]:
a.sum()

14.76606109345805

In [34]:
a.max()

0.9890629256215859

In [35]:
a.mean()

0.590642443738322

In [36]:
a.std()

0.30447963357466773

# Shape and Reshape

In [26]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(np.shape(a))
b = np.array([1,2,3]).reshape(3)
print(np.shape(b))
print(np.dot(a,b))

(4, 3)
(3,)
[14 32 50 68]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(np.shape(a))
b = np.array([1,2,3]).reshape(3,1)
print(np.shape(b))
print(np.dot(a,b))

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(np.shape(a))
b = np.array([1,2,3])
print(np.shape(b))
print(np.dot(a,b))

In [ ]:
print(np.reshape(np.arange(12),(3,-1)))

In [ ]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
a

In [ ]:
x = np.arange(-10,10,.1)
y = np.sin(x)
plt.plot(x,y)

In [ ]:
rnd = np.random.default_rng()

In [ ]:
rnd.random()

In [ ]:
np.random.normal(0, 2, 990) 

In [ ]:
x = np.linspace(-10, 10, 100)
y = - (x**2 + 2*x - 2)  + np.random.normal(0, 8, 100)
plt.scatter(x,y)

In [ ]:
x = rnd.standard_normal(1000)
plt.hist(x)

In [ ]:
x = rnd.standard_normal(1000)
plt.hist(x,15)

In [ ]:
rnd.random((3,3))

In [ ]:
x = np.arange(0,10)
y = x**2
plt.plot(x,y,'g*')

In [ ]:
x = np.arange(0,10)
y = x**2
plt.plot(x,y,'r--')
plt.xlim(2,4)
plt.ylim(3,20)
plt.title("Zoomed")
plt.xlabel("X Axis")
plt.ylabel("Y Axis")

In [ ]:
mat = np.arange(0,100).reshape(10,10)
mat

In [ ]:
plt.imshow(mat)

In [ ]:
mat = np.random.randint(0,100,(10,10))
plt.imshow(mat)

In [ ]:
import matplotlib.image as img
pic = img.imread('pic.jpg')
plt.imshow(pic)

In [ ]:
x = x = np.arange(-100,100,.1)
y1 = x ** 3
y2 = x ** 2
plt.plot(x,y1,'r',x,y2,'g')

In [ ]:
with cbook.get_sample_data('pic.jpg') as file: 
    im = image.imread(file)
    
fig, ax = plt.subplots() 
  
ax.plot(np.cos(10 * np.linspace(0, 1)), '-o', ms = 15, 
                            alpha = 0.6, mfc ='green') 
ax.grid() 
fig.figimage(im, 10, 10, zorder = 3, alpha =.5) 

plt.title('matplotlib.pyplot.imread() function Example',  
                                     fontweight ="bold") 
plt.show()

In [ ]:
plt.plot(x,y1)
plt.title("First plot")

plt.figure()

plt.plot(x,y2)
plt.title("second plot")

In [ ]:
x = np.array([0, 1, 2, 3])
y = np.array([3, 8, 1, 10])

plt.subplot(2, 1, 1)
plt.plot(x,y)

#plot 2:
x = np.array([0, 1, 2, 3])
y = np.array([10, 20, 30, 40])

plt.subplot(2, 1, 2)
plt.plot(x,y)

plt.show()

In [ ]:
x = np.array([0, 1, 2, 3])
y = np.array([3, 8, 1, 10])

plt.subplot(2, 3, 1)
plt.plot(x,y)

y = np.array([10, 20, 30, 40])

plt.subplot(2, 3, 2)
plt.plot(x,y)

y = np.array([3, 8, 1, 10])

plt.subplot(2, 3, 3)
plt.plot(x,y)

y = np.array([10, 20, 30, 40])

plt.subplot(2, 3, 4)
plt.plot(x,y)

y = np.array([3, 8, 1, 10])

plt.subplot(2, 3, 5)
plt.plot(x,y)

y = np.array([10, 20, 30, 40])

plt.subplot(2, 3, 6)
plt.plot(x,y)

plt.show()

In [ ]:
code = np.array([
    1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
    0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
    1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
    1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1])

pixel_per_bar = 4
dpi = 100

fig = plt.figure(figsize=(len(code) * pixel_per_bar / dpi, 2), dpi=dpi)
ax = fig.add_axes([0, 0, 1, 1])  # span the whole figure
ax.set_axis_off()
ax.imshow(code.reshape(1, -1), cmap='binary', aspect='auto',
          interpolation='nearest')
plt.show()